# Generated by Django 3.2.7 on 2021-11-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_tag', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('stocks', models.IntegerField()),
                ('imageURL', models.URLField()),
                ('status', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete', to='EcommerceApi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=155)),
                ('isbn', models.CharField(max_length=15)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('stocks', models.IntegerField()),
                ('description', models.TextField()),
                ('imageURl', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='EcommerceApi.category')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
