# Generated by Django 3.2.7 on 2021-11-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='produce_tag',
            new_name='product_tag',
        ),
    ]
